spring:
  application:
    name: email
  zipkin:
    base-url: http://localhost:9411

  kafka:
    consumer:
      group-id: "default"

  mail:
    host: smtp.gmail.com
    port: 587
    username: mjshop.assistant@gmail.com
    password: wvsqturjfvljjvot

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

topic:
  email: topic.email