server:
  port: 8082
spring:
  application:
    name: room
  datasource:
    url: jdbc:postgresql://postgres:5432/rooms
    username: 'mj'
    password: 'mj'
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
